// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAModQT8ASMlZjO_oqLL7iRZJXYoGaNnEE',
    appId: '1:319869114412:web:74330d5d1bd2b387f65989',
    messagingSenderId: '319869114412',
    projectId: 'untitled4-milan123',
    authDomain: 'untitled4-milan123.firebaseapp.com',
    storageBucket: 'untitled4-milan123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGw_vh-X03hxJw0DvKIUB2SxvxL2KYy4',
    appId: '1:319869114412:android:8d40f5c960f406fbf65989',
    messagingSenderId: '319869114412',
    projectId: 'untitled4-milan123',
    storageBucket: 'untitled4-milan123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD3Hln1GQ6O9j2dpSsX5sZ3zzsboHu9bA',
    appId: '1:319869114412:ios:3d4e6bb1c876292df65989',
    messagingSenderId: '319869114412',
    projectId: 'untitled4-milan123',
    storageBucket: 'untitled4-milan123.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD3Hln1GQ6O9j2dpSsX5sZ3zzsboHu9bA',
    appId: '1:319869114412:ios:3d4e6bb1c876292df65989',
    messagingSenderId: '319869114412',
    projectId: 'untitled4-milan123',
    storageBucket: 'untitled4-milan123.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAModQT8ASMlZjO_oqLL7iRZJXYoGaNnEE',
    appId: '1:319869114412:web:240227c560658b97f65989',
    messagingSenderId: '319869114412',
    projectId: 'untitled4-milan123',
    authDomain: 'untitled4-milan123.firebaseapp.com',
    storageBucket: 'untitled4-milan123.firebasestorage.app',
  );
}
