// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqsBLwf9qevRd3EOBkxSoFb_3rr7YIhDg',
    appId: '1:821354345876:web:c269bcd0636c9854320b81',
    messagingSenderId: '821354345876',
    projectId: 'admin-793a6',
    authDomain: 'admin-793a6.firebaseapp.com',
    storageBucket: 'admin-793a6.firebasestorage.app',
    measurementId: 'G-63EM5C6T13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7-kDvL5ZO1o9QZxs7W4L_XbcMhc3m-Zc',
    appId: '1:821354345876:android:dc33a2625578f43b320b81',
    messagingSenderId: '821354345876',
    projectId: 'admin-793a6',
    storageBucket: 'admin-793a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICvYgwRsE9EDHCdt5KB3ccTzfW6jgAA8',
    appId: '1:821354345876:ios:27e873bef30f8eb4320b81',
    messagingSenderId: '821354345876',
    projectId: 'admin-793a6',
    storageBucket: 'admin-793a6.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqsBLwf9qevRd3EOBkxSoFb_3rr7YIhDg',
    appId: '1:821354345876:web:2399f38ee622dcb0320b81',
    messagingSenderId: '821354345876',
    projectId: 'admin-793a6',
    authDomain: 'admin-793a6.firebaseapp.com',
    storageBucket: 'admin-793a6.firebasestorage.app',
    measurementId: 'G-S0G1FYXW7N',
  );
}
